services:
  client:
    build: ./client
    container_name: mqtt_client
    networks:
      - mqtt_net
    ports:
      - 3000:3000
    depends_on:
      - broker
      - mongo
    environment:
      - MQTT_URL=mqtt://broker
      - MONGODB_URL=mongodb://mongoDB:27017/
      - MONGODB_ADMIN_USERNAME=root
      - MONGODB_ADMIN_PASSWORD=yoUrsAfePa5sWorD09374!#+~123
    env_file:
      - ./client/.env
  mongoDB:
    image: mongo
    container_name: mqtt_db
    networks:
      - mqtt_net
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yoUrsAfePa5sWorD09374!#+~123
  broker:
    build: ./broker
    container_name: mqtt_broker
    networks:
      - mqtt_net
    ports:
      - 1883:1883
      - 8883:8883
    env_file:
      - ./broker/.env
    volumes:
      - broker_data:/mosquitto/data
      - broker_log:/mosquitto/log
networks:
  mqtt_net:
volumes:
  broker_data:
    name: broker_data
  broker_log:
    name: broker_log
  database: 
    name: mongoDB