version: '3.4'
services:
  server:
    build: ./server
    container_name: openwb_server
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 3000:3000
    depends_on:
      - redisDB
    environment:
      REDISDB_URL: redis://redisDB:6379
    volumes:
      - ./test:/app/test
    env_file:
      - ./.env
  redisDB:
    image: redis:alpine
    container_name: openwb_redis
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    ports:
      - 6379:6379
    networks:
      - internal
    volumes:
      - redisDB:/data
networks:
 internal:
volumes:
  redisDB: 
    external: true
    name: redis