version: '3.4'
services:
  server:
    build: ./server
    container_name: openwb_server
    restart: unless-stopped
    networks:
      - internal
    ports:
      - 3000:3000
    depends_on:
      - redisDB
    environment:
      INFLUX_URL: http://influxDB:8086
      REDISDB_URL: redis://redisDB:6379
    volumes:
      - ./test:/app/test
    env_file:
      - ./.env
  redisDB:
    image: redis
    container_name: openwb_redis
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    ports:
      - 6379:6379
    networks:
      - internal
    volumes:
      - redisDB:/data
  mosquitto:
    container_name: openwb_mosquitto
    image: eclipse-mosquitto:2.0-openssl
    volumes:
      - ./broker:/mosquitto/config/
    ports:
      - '8883:8883'
    networks:
      - default
    restart: unless-stopped
networks:
 internal:
volumes:
  redisDB: 
    external: true
    name: redis