services:
  client:
    build: ./client
    env_file:
      - ./client/.env
  broker:
    build: ./broker
    env_file:
      - ./broker/.env
    volumes:
      - broker_config:/mosquitto/config
      - broker_data:/mosquitto/data
      - broker_log:/mosquitto/log

volumes:
  