version: '3.4'
services:
  client:
    build: ./client
    container_name: mqtt_client
    restart: unless-stopped
    networks:
      - mqtt_net
    ports:
      - 3000:3000
    depends_on:
      - broker
      - mongoDB
    environment:
      - MQTT_URL=mqtt://broker
      - MONGODB_URL=mongodb://mongoDB:27017/
    env_file:
      - ./.env
  mongoDB:
    image: mongo
    container_name: mqtt_db
    restart: on-failure
    networks:
      - mqtt_net
    volumes:
      - database:/data/db
    env_file:
      - ./.env
  broker:
    build: ./broker
    container_name: mqtt_broker
    restart: on-failure
    networks:
      - mqtt_net
    ports:
      - 1883:1883
      - 8883:8883
    env_file:
      - ./.env
    volumes:
      - broker_data:/mosquitto/data
      - broker_log:/mosquitto/log
networks:
  mqtt_net:
volumes:
  broker_data:
    external: true
    name: broker_data
  broker_log:
    name: broker_log
  database: 
    external: true
    name: mongoDB