version: '3.4'
services:
  client:
    build: ./client
    container_name: mqtt_client
    restart: unless-stopped
    networks:
      - mqtt_net
    ports:
      - 3000:3000
    depends_on:
      - broker
      - mongoDB
    environment:
      - MONGODB_URL=mongodb://mongoDB:27017/
      - REDISDB_URL=redis://redisDB:6379
    env_file:
      - ./.env
  mongoDB:
    image: mongo
    container_name: mqtt_db
    restart: on-failure
    networks:
      - mqtt_net
    volumes:
      - database:/data/db
    env_file:
      - ./.env
  redisDB:
    image: redis
    container_name: mqtt_redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - mqtt_net
networks:
  mqtt_net:
volumes:
  database: 
    external: true
    name: mongoDB