services:
  client:
    build: ./client
    container_name: mqtt_client
    ports:
      - 3000:3000
    depends_on:
      - broker
    links:
      - broker
    environment:
      - MQTT_URL=mqtt://broker
    env_file:
      - ./client/.env
  broker:
    build: ./broker
    container_name: mqtt_broker
    ports:
      - 1883:1883
      - 9001:9001
    env_file:
      - ./broker/.env
    volumes:
      - broker_config:/mosquitto/config
      - broker_data:/mosquitto/data
      - broker_log:/mosquitto/log

volumes:
  broker_config:
    name: broker_config
  broker_data:
    name: broker_data
  broker_log:
    name: broker_log