version: '3.4'
services:
  client:
    build: ./client
    container_name: mqtt_client
    restart: unless-stopped
    networks:
      - mqtt_net
    ports:
      - 3000:3000
    depends_on:
      - influxDB
      - redisDB
    environment:
      INFLUX_URL: http://influxDB:8086
      REDISDB_URL: redis://redisDB:6379
    volumes:
      - ./test:/app/test
    env_file:
      - ./.env
  influxDB:
    image: influxdb
    container_name: influx_db
    restart: on-failure
    ports:
      - 8086:8086
    networks:
      - mqtt_net
    volumes:
      - influxDB:/var/lib/influxdb2
      - influxDBconf:/etc/influxdb2/influxdb.conf
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: 1+-sd12?!123d+1#12213
      DOCKER_INFLUXDB_INIT_RETENTION_BRUH: The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: aaaaaaaaaaaaaaaaaaaa12332
      INFLUXD_HTTP_BIND_ADDRESS: 0.0.0.0:8086
    env_file:
      - ./.env
  redisDB:
    image: redis
    container_name: mqtt_redis
    restart: on-failure
    ports:
      - 6379:6379
    networks:
      - mqtt_net
    volumes:
      - redisDB:/data
networks:
  mqtt_net:
volumes:
  influxDB: 
    external: true
    name: influx
  influxDBconf: 
    external: true
    name: influx_conf
  redisDB: 
    external: true
    name: redis